# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19215b75dd9d3327f07fd1309988d57f0ba67361f318e65410cbdb200b9ef110f268397c8f2ad698daa2c5929639976e7ec2880a249f738be36f381c48855a5e

test:
  secret_key_base: 39075b10d3b474cfc9a5304ef24ef60a36e18d8d3993f79a1296f4fc692daa5d8fbd5fe89d3f5be35bc446a9fa40347a8449fda10d2bff2beddae4c3391ff47e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
